anarchy_societies = [
    {
        "Citizen Happiness": "low",
        "Economic Stability": "low",
        "Political Stability": "low",
        "Police Strength": "low",
        "Weapon Access": "yes",
        "Herd Mentality": "low",
        "Ideology": ["monarchy", "autocracy"],
        "Anarchy": "yes",
    },
    {
        "Citizen Happiness": "low",
        "Economic Stability": "med",
        "Political Stability": "low",
        "Police Strength": "low",
        "Weapon Access": "yes",
        "Herd Mentality": "high",
        "Ideology": ["democracy"],
        "Anarchy": "yes",
    },
    {
        "Citizen Happiness": "low",
        "Economic Stability": "med",
        "Political Stability": "low",
        "Police Strength": "low",
        "Weapon Access": "yes",
        "Herd Mentality": "high",
        "Ideology": ["socialism", "marxism", "communism"],
        "Anarchy": "yes",
    },
    {
        "Citizen Happiness": "low",
        "Economic Stability": "med",
        "Political Stability": "low",
        "Police Strength": "low",
        "Weapon Access": "yes",
        "Herd Mentality": "med",
        "Ideology": ["democracy"],
        "Anarchy": "yes",
    },
    {
        "Citizen Happiness": "med",
        "Economic Stability": "med",
        "Political Stability": "med",
        "Police Strength": "high",
        "Weapon Access": "no",
        "Herd Mentality": "high",
        "Ideology": ["monarchy", "autocracy"],
        "Anarchy": "yes",
    },
    {
        "Citizen Happiness": "low",
        "Economic Stability": "med",
        "Political Stability": "low",
        "Police Strength": "high",
        "Weapon Access": "no",
        "Herd Mentality": "med",
        "Ideology": ["anarchism"],
        "Anarchy": "yes",
    },
    {
        "Citizen Happiness": "low",
        "Economic Stability": "low",
        "Political Stability": "med",
        "Police Strength": "low",
        "Weapon Access": "yes",
        "Herd Mentality": "high",
        "Ideology": ["fascism"],
        "Anarchy": "yes",
    },
    {
        "Citizen Happiness": "low",
        "Economic Stability": "low",
        "Political Stability": "high",
        "Police Strength": "med",
        "Weapon Access": "yes",
        "Herd Mentality": "low",
        "Ideology": ["monarchy"],
        "Anarchy": "yes",
    },
    {
        "Citizen Happiness": "low",
        "Economic Stability": "low",
        "Political Stability": "low",
        "Police Strength": "med",
        "Weapon Access": "yes",
        "Herd Mentality": "high",
        "Ideology": ["communism"],
        "Anarchy": "yes",
    },
    {
        "Citizen Happiness": "low",
        "Economic Stability": "low",
        "Political Stability": "med",
        "Police Strength": "high",
        "Weapon Access": "no",
        "Herd Mentality": "med",
        "Ideology": ["autocracy"],
        "Anarchy": "yes",
    },
    {
        "Citizen Happiness": "low",
        "Economic Stability": "low",
        "Political Stability": "low",
        "Police Strength": "low",
        "Weapon Access": "no",
        "Herd Mentality": "low",
        "Ideology": ["anarchism", "communism"],
        "Anarchy": "yes",
    },
    {
        "Citizen Happiness": "low",
        "Economic Stability": "med",
        "Political Stability": "low",
        "Police Strength": "med",
        "Weapon Access": "yes",
        "Herd Mentality": "low",
        "Ideology": ["fascism", "marxism"],
        "Anarchy": "yes",
    },
    {
        "Citizen Happiness": "med",
        "Economic Stability": "med",
        "Political Stability": "med",
        "Police Strength": "low",
        "Weapon Access": "no",
        "Herd Mentality": "high",
        "Ideology": ["autocracy"],
        "Anarchy": "yes",
    },
    {
        "Citizen Happiness": "med",
        "Economic Stability": "low",
        "Political Stability": "low",
        "Police Strength": "low",
        "Weapon Access": "yes",
        "Herd Mentality": "low",
        "Ideology": ["anarchism", "communism"],
        "Anarchy": "yes",
    },
    {
        "Citizen Happiness": "med",
        "Economic Stability": "med",
        "Political Stability": "low",
        "Police Strength": "med",
        "Weapon Access": "yes",
        "Herd Mentality": "low",
        "Ideology": ["fascism", "marxism"],
        "Anarchy": "yes",
    },
    {
        "Citizen Happiness": "med",
        "Economic Stability": "low",
        "Political Stability": "med",
        "Police Strength": "low",
        "Weapon Access": "yes",
        "Herd Mentality": "low",
        "Ideology": ["autocracy"],
        "Anarchy": "yes",
    },
    {
        "Citizen Happiness": "low",
        "Economic Stability": "low",
        "Political Stability": "low",
        "Police Strength": "low",
        "Weapon Access": "no",
        "Herd Mentality": "high",
        "Ideology": ["anarchism", "socialism"],
        "Anarchy": "yes",
    },
    {
        "Citizen Happiness": "low",
        "Economic Stability": "low",
        "Political Stability": "high",
        "Police Strength": "low",
        "Weapon Access": "yes",
        "Herd Mentality": "low",
        "Ideology": ["anarchism", "communism"],
        "Anarchy": "yes",
    },
    {
        "Citizen Happiness": "low",
        "Economic Stability": "med",
        "Political Stability": "low",
        "Police Strength": "low",
        "Weapon Access": "yes",
        "Herd Mentality": "high",
        "Ideology": ["anarchism", "communism"],
        "Anarchy": "yes",
    },
    {
        "Citizen Happiness": "low",
        "Economic Stability": "med",
        "Political Stability": "med",
        "Police Strength": "med",
        "Weapon Access": "med",
        "Herd Mentality": "high",
        "Ideology": ["socialism"],
        "Anarchy": "yes",
    },
    {
        "Citizen Happiness": "med",
        "Economic Stability": "low",
        "Political Stability": "low",
        "Police Strength": "low",
        "Weapon Access": "yes",
        "Herd Mentality": "med",
        "Ideology": ["anarchism", "fascism"],
        "Anarchy": "yes",
    },
    {
        "Citizen Happiness": "med",
        "Economic Stability": "low",
        "Political Stability": "med",
        "Police Strength": "low",
        "Weapon Access": "yes",
        "Herd Mentality": "high",
        "Ideology": ["autocracy", "marxism"],
        "Anarchy": "yes",
    },
    {
        "Citizen Happiness": "med",
        "Economic Stability": "med",
        "Political Stability": "low",
        "Police Strength": "low",
        "Weapon Access": "yes",
        "Herd Mentality": "low",
        "Ideology": ["anarchism", "socialism"],
        "Anarchy": "yes",
    },
]

societies = [
    {
        "Citizen Happiness": "high",
        "Economic Stability": "med",
        "Political Stability": "high",
        "Police Strength": "med",
        "Weapon Access": "yes",
        "Herd Mentality": "med",
        "Ideology": ["democracy"],
        "Anarchy": "no",
    },
    {
        "Citizen Happiness": "high",
        "Economic Stability": "med",
        "Political Stability": "high",
        "Police Strength": "high",
        "Weapon Access": "no",
        "Herd Mentality": "low",
        "Ideology": ["constitutional monarchy", "democracy"],
        "Anarchy": "no",
    },
    {
        "Citizen Happiness": "med",
        "Economic Stability": "med",
        "Political Stability": "high",
        "Police Strength": "med",
        "Weapon Access": "no",
        "Herd Mentality": "med",
        "Ideology": ["democracy"],
        "Anarchy": "no",
    },
    {
        "Citizen Happiness": "med",
        "Economic Stability": "high",
        "Political Stability": "high",
        "Police Strength": "high",
        "Weapon Access": "no",
        "Herd Mentality": "low",
        "Ideology": ["democracy", "parliamentarian democracy"],
        "Anarchy": "no",
    },
    {
        "Citizen Happiness": "med",
        "Economic Stability": "high",
        "Political Stability": "high",
        "Police Strength": "high",
        "Weapon Access": "no",
        "Herd Mentality": "low",
        "Ideology": ["democracy", "constitutional monarchy"],
        "Anarchy": "no",
    },
    {
        "Citizen Happiness": "high",
        "Economic Stability": "high",
        "Political Stability": "high",
        "Police Strength": "high",
        "Weapon Access": "no",
        "Herd Mentality": "high",
        "Ideology": ["autocracy", "communism"],
        "Anarchy": "no",
    },
    {
        "Citizen Happiness": "med",
        "Economic Stability": "high",
        "Political Stability": "high",
        "Police Strength": "high",
        "Weapon Access": "no",
        "Herd Mentality": "med",
        "Ideology": ["parliamentarian democracy", "socialism"],
        "Anarchy": "no",
    },
    {
        "Citizen Happiness": "high",
        "Economic Stability": "med",
        "Political Stability": "med",
        "Police Strength": "high",
        "Weapon Access": "yes",
        "Herd Mentality": "high",
        "Ideology": ["monarchy", "autocracy"],
        "Anarchy": "no",
    },
    {
        "Citizen Happiness": "high",
        "Economic Stability": "med",
        "Political Stability": "med",
        "Police Strength": "med",
        "Weapon Access": "yes",
        "Herd Mentality": "high",
        "Ideology": ["democracy", "socialism"],
        "Anarchy": "no",
    },
    {
        "Citizen Happiness": "med",
        "Economic Stability": "med",
        "Political Stability": "high",
        "Police Strength": "high",
        "Weapon Access": "no",
        "Herd Mentality": "low",
        "Ideology": ["democracy", "parliamentarian democracy"],
        "Anarchy": "no",
    },
    {
        "Citizen Happiness": "med",
        "Economic Stability": "high",
        "Political Stability": "high",
        "Police Strength": "high",
        "Weapon Access": "no",
        "Herd Mentality": "high",
        "Ideology": ["democracy", "liberalism"],
        "Anarchy": "no",
    },
    {
        "Citizen Happiness": "med",
        "Economic Stability": "med",
        "Political Stability": "high",
        "Police Strength": "high",
        "Weapon Access": "no",
        "Herd Mentality": "low",
        "Ideology": ["democracy", "parliamentarian democracy"],
        "Anarchy": "no",
    },
    {
        "Citizen Happiness": "med",
        "Economic Stability": "high",
        "Political Stability": "high",
        "Police Strength": "high",
        "Weapon Access": "yes",
        "Herd Mentality": "high",
        "Ideology": ["monarchy", "autocracy"],
        "Anarchy": "no",
    },
    {
        "Citizen Happiness": "high",
        "Economic Stability": "high",
        "Political Stability": "high",
        "Police Strength": "high",
        "Weapon Access": "no",
        "Herd Mentality": "med",
        "Ideology": ["socialism", "communism"],
        "Anarchy": "no",
    },
    {
        "Citizen Happiness": "high",
        "Economic Stability": "high",
        "Political Stability": "low",
        "Police Strength": "med",
        "Weapon Access": "yes",
        "Herd Mentality": "low",
        "Ideology": ["fascism", "marxism"],
        "Anarchy": "no",
    },
    {
        "Citizen Happiness": "high",
        "Economic Stability": "high",
        "Political Stability": "med",
        "Police Strength": "low",
        "Weapon Access": "no",
        "Herd Mentality": "low",
        "Ideology": ["democracy"],
        "Anarchy": "no",
    },
    {
        "Citizen Happiness": "med",
        "Economic Stability": "med",
        "Political Stability": "high",
        "Police Strength": "high",
        "Weapon Access": "no",
        "Herd Mentality": "high",
        "Ideology": ["constitutional monarchy"],
        "Anarchy": "no",
    },
    {
        "Citizen Happiness": "high",
        "Economic Stability": "med",
        "Political Stability": "low",
        "Police Strength": "med",
        "Weapon Access": "yes",
        "Herd Mentality": "high",
        "Ideology": ["anarchism", "socialism"],
        "Anarchy": "no",
    },
    {
        "Citizen Happiness": "med",
        "Economic Stability": "med",
        "Political Stability": "high",
        "Police Strength": "high",
        "Weapon Access": "no",
        "Herd Mentality": "high",
        "Ideology": ["democracy", "libertarianism"],
        "Anarchy": "no",
    },
    {
        "Citizen Happiness": "med",
        "Economic Stability": "med",
        "Political Stability": "med",
        "Police Strength": "high",
        "Weapon Access": "no",
        "Herd Mentality": "low",
        "Ideology": ["monarchy", "fascism"],
        "Anarchy": "no",
    },
    {
        "Citizen Happiness": "med",
        "Economic Stability": "med",
        "Political Stability": "high",
        "Police Strength": "high",
        "Weapon Access": "no",
        "Herd Mentality": "high",
        "Ideology": ["democracy", "socialism"],
        "Anarchy": "no",
    },
    {
        "Citizen Happiness": "med",
        "Economic Stability": "high",
        "Political Stability": "low",
        "Police Strength": "low",
        "Weapon Access": "yes",
        "Herd Mentality": "low",
        "Ideology": ["autocracy", "fascism"],
        "Anarchy": "no",
    },
    {
        "Citizen Happiness": "med",
        "Economic Stability": "high",
        "Political Stability": "med",
        "Police Strength": "med",
        "Weapon Access": "no",
        "Herd Mentality": "high",
        "Ideology": ["democracy", "social democracy"],
        "Anarchy": "no",
    },
    {
        "Citizen Happiness": "med",
        "Economic Stability": "high",
        "Political Stability": "low",
        "Police Strength": "low",
        "Weapon Access": "yes",
        "Herd Mentality": "low",
        "Ideology": ["anarchism", "socialism"],
        "Anarchy": "no",
    },
    {
        "Citizen Happiness": "med",
        "Economic Stability": "med",
        "Political Stability": "high",
        "Police Strength": "high",
        "Weapon Access": "yes",
        "Herd Mentality": "low",
        "Ideology": ["monarchy"],
        "Anarchy": "no",
    },
]
